Fix final exit code

diff --git a/.github/workflows/check-meta.yml b/.github/workflows/check-meta.yml
--- a/.github/workflows/check-meta.yml
+++ b/.github/workflows/check-meta.yml
@@ -12,5 +12,4 @@ jobs:
           for d in */; do
             [[ -z $(yq read .meta/logos.yaml "(id==${d%/})") ]] && missing+=("${d%/}")
           done
-          echo "${missing[@]}"
-          [[ -n "${missing[@]}" ]] && { echo "Logo IDs missing from meta file (.meta/logos.yaml): ${missing[@]}"; exit 1; }
+          [[ -n "${missing[@]}" ]] && { echo "Logo IDs missing from meta file (.meta/logos.yaml): ${missing[@]}"; exit 1; } || exit 0
